/**
 * Created by Ken
 * Task No. 56996
 * 3/31/2022
 */
public with sharing class SIP_SumConsumedGroupRule extends SIP_Rule{

    /**
     * SIP_SumConsumedGroupRule
     */
    public SIP_SumConsumedGroupRule() {
        //super();
    }

    /**
     * Execute
     */
    public override void execute() {
        System.debug('Inside SIP_SumConsumedGroupRule class in execute method');
        //super.execute();
    }

}